[2023-08-22T01:47:38.082+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Investimento_api.Extracao_Invest manual__2023-08-22T01:47:36.341330+00:00 [queued]>
[2023-08-22T01:47:38.091+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Investimento_api.Extracao_Invest manual__2023-08-22T01:47:36.341330+00:00 [queued]>
[2023-08-22T01:47:38.092+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-08-22T01:47:38.105+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): Extracao_Invest> on 2023-08-22 01:47:36.341330+00:00
[2023-08-22T01:47:38.109+0000] {standard_task_runner.py:57} INFO - Started process 381 to run task
[2023-08-22T01:47:38.113+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'Investimento_api', 'Extracao_Invest', 'manual__2023-08-22T01:47:36.341330+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpnlhbgkab']
[2023-08-22T01:47:38.117+0000] {standard_task_runner.py:85} INFO - Job 127: Subtask Extracao_Invest
[2023-08-22T01:47:38.170+0000] {task_command.py:415} INFO - Running <TaskInstance: Investimento_api.Extracao_Invest manual__2023-08-22T01:47:36.341330+00:00 [running]> on host e8c02fb45ab3
[2023-08-22T01:47:38.241+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Investimento_api' AIRFLOW_CTX_TASK_ID='Extracao_Invest' AIRFLOW_CTX_EXECUTION_DATE='2023-08-22T01:47:36.341330+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-22T01:47:36.341330+00:00'
[2023-08-22T01:47:38.250+0000] {spark_submit.py:218} INFO - Could not load connection string spark-submit, defaulting to yarn
[2023-08-22T01:47:38.251+0000] {spark_submit.py:340} INFO - Spark-Submit cmd: spark-submit --master yarn --name Extracao_Invest ../operators/Raw_Operator.py
[2023-08-22T01:47:39.238+0000] {spark_submit.py:491} INFO - WARNING: An illegal reflective access operation has occurred
[2023-08-22T01:47:39.239+0000] {spark_submit.py:491} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.8/site-packages/pyspark/jars/spark-unsafe_2.12-3.2.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2023-08-22T01:47:39.239+0000] {spark_submit.py:491} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2023-08-22T01:47:39.240+0000] {spark_submit.py:491} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2023-08-22T01:47:39.240+0000] {spark_submit.py:491} INFO - WARNING: All illegal access operations will be denied in a future release
[2023-08-22T01:47:39.277+0000] {spark_submit.py:491} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2023-08-22T01:47:39.277+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:634)
[2023-08-22T01:47:39.278+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:274)
[2023-08-22T01:47:39.278+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:234)
[2023-08-22T01:47:39.279+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:119)
[2023-08-22T01:47:39.280+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1026)
[2023-08-22T01:47:39.280+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1026)
[2023-08-22T01:47:39.281+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:85)
[2023-08-22T01:47:39.281+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1043)
[2023-08-22T01:47:39.281+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1052)
[2023-08-22T01:47:39.282+0000] {spark_submit.py:491} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2023-08-22T01:47:39.295+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 156, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 422, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name Extracao_Invest ../operators/Raw_Operator.py. Error code is: 1.
[2023-08-22T01:47:39.298+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=Investimento_api, task_id=Extracao_Invest, execution_date=20230822T014736, start_date=20230822T014738, end_date=20230822T014739
[2023-08-22T01:47:39.311+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 127 for task Extracao_Invest (Cannot execute: spark-submit --master yarn --name Extracao_Invest ../operators/Raw_Operator.py. Error code is: 1.; 381)
[2023-08-22T01:47:39.329+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-22T01:47:39.352+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
